Added workflow timing
LinuxForHealth/connect pull request #183
Opened 2021-05-11 15:27 UTC by ccorley

Added a single timer decorator that works for both async and sync functions.

With trace logging enabled:
```
2021-05-11 15:35:54,188 - uvicorn.error - INFO - Application startup complete.
2021-05-11 15:37:45,613 - connect.workflows.core - TRACE - Running FhirWorkflow
2021-05-11 15:37:45,613 - connect.workflows.fhir - TRACE - FhirWorkflow.validate: resource type = Patient
2021-05-11 15:37:45,707 - connect.workflows.core - TRACE - validate() id = d58d4e34-0d1a-433d-af7a-a467af898b16 elapsed time = 0.0939889s
2021-05-11 15:37:45,707 - connect.workflows.core - TRACE - transform() id = d58d4e34-0d1a-433d-af7a-a467af898b16 elapsed time = 0.0000060s
2021-05-11 15:37:45,707 - connect.workflows.core - TRACE - FhirWorkflow: incoming message type = <class 'fhir.resources.patient.Patient'>
2021-05-11 15:37:46,312 - connect.clients.kafka - TRACE - Produced record to topic FHIR-R4_PATIENT partition [0] @ offset 8804
2021-05-11 15:37:46,313 - connect.workflows.core - TRACE -  FhirWorkflow persist: stored resource location = FHIR-R4_PATIENT:0:8804
2021-05-11 15:37:46,313 - connect.workflows.core - TRACE - persist() id = d58d4e34-0d1a-433d-af7a-a467af898b16 elapsed time = 0.6056950s
2021-05-11 15:37:46,313 - connect.workflows.core - TRACE - transmit() id = d58d4e34-0d1a-433d-af7a-a467af898b16 elapsed time = 0.0000126s
2021-05-11 15:37:46,314 - connect.workflows.core - TRACE - synchronize() id = d58d4e34-0d1a-433d-af7a-a467af898b16 elapsed time = 0.0001521s
2021-05-11 15:37:46,314 - connect.workflows.core - TRACE - run() id = d58d4e34-0d1a-433d-af7a-a467af898b16 elapsed time = 0.7009690s
2021-05-11 15:37:46,315 - uvicorn.access - INFO - 127.0.0.1:54987 - "POST /fhir/Patient HTTP/1.1" 200
2021-05-11 15:37:46,319 - connect.clients.nats - TRACE - nats_sync_event_handler: received a message on EVENTS.sync 
2021-05-11 15:37:46,319 - connect.clients.nats - TRACE - nats_sync_event_handler: detected local LFH message, not storing in kafka
```

2021-05-11 16:03 UTC, dixonwhitmire requested changes
Hi @ccorley ! This is looking good. I think you may be able to consolidate to a single decorator using the `inspect` module. Let me know what you think.
Thanks!

2021-05-11 16:03 UTC, dixonwhitmire commented on connect/support/timer.py
> +    """Async decorator to print the elapsed runtime of the decorated function"""
You may be able to switch using the `inspect` module. https://docs.python.org/3/library/inspect.html#inspect.iscoroutinefunction

The other approach, asyncio.iscoroutinefunction was used for "legacy" asyncio implementations that relied on decorators, I think.

2021-05-11 16:03 UTC, dixonwhitmire commented on connect/support/timer.py
> +        start_time = time.time()
I would opt to check to see if the timing is enabled before starting/stopping timers.

2021-05-11 16:36 UTC, ccorley commented on connect/support/timer.py
> +        start_time = time.time()
Yup, that was the other option.  done.

2021-05-11 17:51 UTC, ccorley commented on connect/support/timer.py
> +    """Async decorator to print the elapsed runtime of the decorated function"""
The net from this is that we can use one decorator, whether a method decorated with `@timer` is sync or async, but we always need to await the method due to the decorator.  So when the decorated workflow step is called from the workflow run() or from any tests, it needs to be awaited.  The code now uses one decorator.

2021-05-11 17:51 UTC, dixonwhitmire approved these changes

2021-05-12 14:11 UTC, ccorley commented
Added connect/support/timer.py for timing of non-workflow functions & tested against the primary function of the /data endpoint:
```
@router.get("")
@timer
async def get_data_record(dataformat: str, partition: int, offset: int):
```
Result:
```
2021-05-12 09:07:34,317 - connect.support.timer - TRACE - get_data_record() elapsed time = 1.1635346s
```

2021-05-12 14:37 UTC, merged