Ethereum client addition
LinuxForHealth/connect pull request #214
Opened 2021-06-16 06:04 UTC by cdanup1

This PR adds a generic ethereum client to `connect`

2021-06-16 14:25 UTC, dixonwhitmire reviewed
Hey @cdanup1 - great work on the Ethereum Client! I have a few remarks for you to review in regards to maintaining and evaluating the current state of the client connection.

2021-06-16 14:25 UTC, dixonwhitmire commented on connect/clients/ethereum.py
> +        self._connected = False
not that you need to do it here, but FYI you can also use type hints for local variables and instance attributes
```
self._connected: bool = False
```

It may be helpful for other options which are initialized to None. In those case you can use the Union or Optional type hint . . . .

```
self._client_connect: Union[None, <the type>] = None
OR
self._client_connect: Optional[<the type>] = None
```

I tend to prefer the former but it's just a personal preference.

2021-06-16 14:25 UTC, dixonwhitmire commented on connect/clients/ethereum.py
> +        self._client_connection = None
From a naming and usage standpoint, we may be able to streamline things a bit by just supporting a `self._client` attribute. Then you could use `self._client.isConnected()` rather than having to manage the connection state in a separate boolean.

2021-06-16 14:25 UTC, dixonwhitmire commented on connect/clients/ethereum.py
> +        self._client_connection = Web3(Web3.HTTPProvider(self._eth_network_uri))
To the point above. I tested a bit and confirmed that the Web3 client doesn't raise an exception when initialized. In the snippet below I don't have an eth node running or access to one. Additional the URL can be None and no exception is raised.
```
>>> from web3 import Web3
>>> client =  Web3(Web3.HTTPProvider("http://127.0.0.1:8545"))
>>> client.isConnected()
False

>>> client =  Web3(Web3.HTTPProvider(None))
>>> client.isConnected()
False
```
With that in mind I would recommend opting for a single `self._client_connection` or `self._client` attribute and just check the `isConnected()` method.

2021-06-16 14:27 UTC, ccorley requested changes
This is a great first step - I'm excited that you have the Ethereum client API working!  In terms of integration with connect, we want to turn this into a service that can be integrated as an optional service with its own profile within the connect docker-compose.yml.  Within that service, there needs to be a NATS subscriber/listener that can receive sync messages and send those to Ethereum.

2021-06-17 05:06 UTC, cdanup1 commented on connect/clients/ethereum.py
> +        self._connected = False
Thank you for this. I used the Optional construct from the typing module

2021-06-17 14:46 UTC, dixonwhitmire commented
@cdanup1 I've reached out to a web3.py maintainer regarding the transitive dependency issue - https://github.com/ethereum/web3.py/pull/2029.

Our issue is that uvicorn[standard] is compatible with websockets >= 9.1 while the eth client, web3.py, is configured to use websockets >= 8.0 < 9.0

2021-08-10 00:58 UTC, dixonwhitmire commented
The web3.py, eth client, has been updated to support websockets >= 9.1 < 10. We can try bumping the dependency to resolve this conflict.

2021-08-30 14:59 UTC, ccorley commented
We may need the general client in this PR later.

2021-08-30 14:59 UTC, closed without merging